server.port=${PORT:8080}
spring.application.name=sales-system-unifacisa-fullstack
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
jwt.public.key=classpath:public_key.pem
jwt.private.key=classpath:private_key.pem